---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_REDIS_CACHE_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_CACHE_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_DB: {{ .Values.app.redis.cache_db | quote }}
  APP_ELASTIC_URL: {{ .Values.app.elastic_url | quote }}
  APP_MONGODB_SERVER: {{ .Values.app.mongodb.server | quote }}
  APP_MONGODB_PORT: {{ .Values.app.mongodb.port | quote }}
  APP_MONGODB_DB: {{ .Values.app.mongodb.database | quote }}
  PHP_PM_MAX_CHILDREN: {{ .Values.app.php.max_children | quote }}
  PHP_PM_START_SERVERS: {{ .Values.app.php.start_servers | quote }}
  PHP_PM_MIN_SPARE_SERVERS: {{ .Values.app.php.min_spare_servers | quote }}
  PHP_PM_MAX_SPARE_SERVERS: {{ .Values.app.php.max_spare_servers | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  PHP_FPM_SERVER: '127.0.0.1'
  PHP_FPM_SERVER_PORT: '9000'
