{{- if eq .Values.env "prod" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: ''
  APP_MONGODB_USER: ''
  APP_MONGODB_PASSWORD: ''
  APP_OPENPLATFORM_ID: ''
  APP_OPENPLATFORM_SECRET: ''
  APP_OPENPLATFORM_ALLOWED_CLIENTS: ''
{{- end }}
{{- if eq .Values.env "stg" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: ''
  APP_MONGODB_USER: ''
  APP_MONGODB_PASSWORD: ''
  APP_OPENPLATFORM_ID: ''
  APP_OPENPLATFORM_SECRET: ''
  APP_OPENPLATFORM_ALLOWED_CLIENTS: ''
{{- end }}
{{- if .Values.ingress.enableAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-basic-auth
type: Opaque
data:
  auth: ''
{{- end }}