---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-service
  labels:
    tier: frontend
spec:
  selector:
    app: {{ .Release.Namespace }}-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
