---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: mongodb-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.app.mongodb.storage.class }}
  resources:
    requests:
      storage: {{ .Values.app.mongodb.storage.size }}