services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    # Manually wire the token.cache to ensure the same instance is injected in both Application and Behat Context
    App\Tests\Behat\AuthContext:
        autowire: false
        arguments:
            $tokenCache: '@token.cache'