apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cover-service
  name: mongodb-managed-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain
  resources:
    requests:
      storage: 30Gi